name: CI-STM32CubeIDE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: self-hosted  # Use self-hosted runner if required
    container:
      image: prynceseitenfus/STM32CubeIDE:1.18.1  # Use your Docker Hub image as the container

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          context: ./TCC/test-board
          file: ./TCC/Dockerfile
          push: true
          tags: |
            prynceseitenfus/test-board:${{ github.run_number }}
            prynceseitenfus/test-board:latest