name: CI-class-pipeline

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup do NodeJS
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 16.13.2

      - name: Install Mocha test and packages
        run:
          cd Disciplina-04/convert-temp/src;
          npm install -g mocha;
          npm install

      - name: Test execution
        run: mocha Disciplina-04/convert-temp/src/test/convert.js

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        uses: docker/login-action@v3.4.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        uses: docker/build-push-action@v2.9.0
        with:
          context: ./Disciplina-04/convert-temp/src
          file: ./Disciplina-04/convert-temp/src/Dockerfile
          push: true
          tags: |
            prynceseitenfus/aula-conversao-temperatura:${{github.run_number}}
            prynceseitenfus/aula-conversao-temperatura:latest

