name: pipe-test-board

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    container:
      image: prynceseitenfus/stm32cubeide:1.18.1

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Run build.sh
        run: ./TCC/test-board/build.sh