name: pipe-test-board

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull LFS files
        run: git lfs pull

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          context: ./TCC
          file: ./TCC/Dockerfile
          push: true
          tags: |
            prynceseitenfus/test-board:${{ github.run_number }}
            prynceseitenfus/test-board:latest